- hosts: all
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.HOME  }}/.cargo/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Install rust
      shell: curl https://sh.rustup.rs -sSf > rust-install && sh rust-install -y && rm rust-install
    - name: Install nightly toolchain
      command: rustup install nightly
    - name: Add rust source
      command: rustup component add rust-src
    - name: Add rustfmt
      command: rustup component add rustfmt
    - name: Add clippy
      command: rustup component add clippy
    - name: Install racer
      command: cargo +nightly install racer -f
    - name: Install cargo-watch
      command: cargo install cargo-watch -f
    - name: Install cargo-oudated
      command: cargo install cargo-outdated -f
    - name: Install cargo-edit
      command: cargo install cargo-edit -f
    - name: Install cargo-update
      command: cargo install cargo-update -f
